const dbMenu = {
	cake: [
		{
			name: 'Berry cake',
			img: '/menu/cakes/berry_cake.jpg',
			id: 1,
			price: 11,
			toppings: ['Cream', 'Jam', 'Chocolate', 'Caramel', 'Biscuits', 'Vanilla', 'Coconut', 'Grape'],
			categories: 'Cake',
		},
		{
			name: 'Blackberry cake',
			img: '/menu/cakes/blackberry_cake.jpg',
			id: 2,
			price: 9,
			toppings: ['Cream', 'Jam', 'Biscuits', 'Coconut'],
			categories: 'Cake',
		},
		{
			name: 'Chocolate cake',
			img: '/menu/cakes/chocolate_cake.jpg',
			id: 3,
			price: 6,
			toppings: ['Strawberry', 'Cherry', 'Grape', 'Raspberry'],
			categories: 'Cake',
		},
		{
			name: 'Fig cake',
			img: '/menu/cakes/fig_cake.jpg',
			id: 4,
			price: 20,
			categories: 'Cake',
		},
		{
			name: 'Raspberry cake',
			img: '/menu/cakes/raspberry_cake.jpg',
			id: 5,
			price: 15,
			toppings: ['Cream', 'Caramel', 'Chocolate', 'Coconut'],
			categories: 'Cake',
		},
		{
			name: 'Strawberry cake',
			img: '/menu/cakes/strawberry_cake.jpg',
			id: 6,
			price: 25,
			toppings: ['Cream', 'Jam', 'Biscuits', 'Coconut'],
			categories: 'Cake',
		},
	],
	cupcake: [
		{
			name: 'Chocolate cupcake',
			img: '/menu/cupcakes/chocolate_cupcake.jpg',
			id: 1,
			price: 3,
			toppings: ['Bonbon', 'Jam', 'Biscuits', 'Coconut'],
			categories: 'Cupcake',
		},
		{
			name: 'Macaroon cupcake',
			img: '/menu/cupcakes/macaroon_cupcake.jpg',
			id: 2,
			price: 5,
			categories: 'Cupcake',
		},
		{
			name: 'Mint cupcake',
			img: '/menu/cupcakes/mint_cupcake.jpg',
			id: 3,
			price: 2,
			toppings: ['Bonbon', 'Jam', 'Biscuits', 'Coconut'],
			categories: 'Cupcake',
		},
		{
			name: 'Ninja cupcake',
			img: '/menu/cupcakes/ninja_cupcake.jpg',
			id: 4,
			price: 5,
			categories: 'Cupcake',
		},
		{
			name: 'Pig cupcake',
			img: '/menu/cupcakes/pig_cupcake.jpg',
			id: 5,
			price: 3,
			categories: 'Cupcake',
		},
		{
			name: 'Rainbow cupcake',
			img: '/menu/cupcakes/rainbow_cupcake.jpg',
			id: 6,
			price: 3,
			toppings: ['Bonbon', 'Jam', 'Biscuits', 'Coconut'],
			categories: 'Cupcake',
		},
	],
	other: [
		{
			name: 'Biscuits',
			img: '/menu/other/biscuits.jpg',
			id: 1,
			price: 1,
			choices: ['Jam', 'Chocolate', 'Caramel', 'Vanilla'],
			categories: 'Bakery products',
		},
		{
			name: 'Donuts',
			img: '/menu/other/donuts.jpg',
			id: 2,
			price: 2,
			choices: ['Jam', 'Chocolate', 'Caramel', 'Vanilla'],
			categories: 'Bakery products',
		},
		{
			name: 'Macaroons',
			img: '/menu/other/macaroons.jpg',
			id: 3,
			price: 15,
			choices: ['Banana', 'Strawberry', 'Сherry', 'Mint'],
			categories: 'Bakery products',
		},
		{
			name: 'Tarts',
			img: '/menu/other/tarts.jpg',
			id: 4,
			price: 3,
			choices: ['Berry', 'Jam', 'Grape', 'Strawberry'],
			categories: 'Bakery products',
		},
	],
	drinks: [
		{
			name: 'Soda',
			img: '/menu/drinks/soda.jpg',
			id: 1,
			price: 1,
			choices: ['Coca-cola', 'Fanta', 'Mirinda', 'Sprite'],
			categories: 'Drinks',
		},
		{
			name: 'Tea',
			img: '/menu/drinks/tea.jpg',
			id: 2,
			price: 3,
			choices: ['White', 'Green', 'Black', 'Herbs'],
			categories: 'Drinks',
		},
		{
			name: 'Smoothie',
			img: '/menu/drinks/smoothie.jpg',
			id: 3,
			price: 4,
			choices: ['Banana', 'Avocado', 'Сherry'],
			categories: 'Drinks',
		},
		{
			name: 'Coffee',
			img: '/menu/drinks/coffee.jpg',
			id: 4,
			price: 3,
			choices: ['Espresso', 'Cappuccino', 'Latte', 'Macchiato'],
			categories: 'Drinks',
		},
	]
};

export default dbMenu;
